# Generated by Django 4.0.1 on 2022-01-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='is_donor',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='authuser',
            old_name='is_useradmin',
            new_name='is_user',
        ),
    ]
